"""Add city to franchise

Revision ID: 1b64ead41c04
Revises: 56a80bfaa95e
Create Date: 2023-07-11 17:28:22.503040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b64ead41c04'
down_revision = '56a80bfaa95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchise', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
