"""Franchise table

Revision ID: 56a80bfaa95e
Revises: e2cb723f0c2c
Create Date: 2023-06-30 23:56:21.979938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a80bfaa95e'
down_revision = 'e2cb723f0c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['organization_id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
