"""empty message

Revision ID: 5e17fbfb4064
Revises: d35d1b1b3bef
Create Date: 2023-06-22 15:19:04.783975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e17fbfb4064'
down_revision = 'd35d1b1b3bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'CUSTOMER', 'SUPER_ADMIN'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'CUSTOMER', 'SUPER_ADMIN'),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
