"""Update user model

Revision ID: d35d1b1b3bef
Revises: d5b297bb9751
Create Date: 2023-06-21 22:25:24.997887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35d1b1b3bef'
down_revision = 'd5b297bb9751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
