"""Cascade on delete

Revision ID: f2c67d8a3684
Revises: 398fa16eb17f
Create Date: 2023-06-30 23:13:33.882873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c67d8a3684'
down_revision = '398fa16eb17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('organization_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('organization_ibfk_1', 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###
